apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: ypd04208625/kub-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default" # CoreDNS로 할당
            - name: TASKS_FOLDER
              value: tasks